sudo: false
git:
  depth: false

language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - pypy

install:
  - python -m pip install -U pip setuptools
  - pip install -U -r requirements.txt
  - pip install -U -e .

  - cd test && pip uninstall --yes jinjatools && cd ..
  - pip install -e .
  - pip install -U -r test-requirements.txt
  - pip install -U tox tox-travis

script:
  - py.test -vv --doctest-modules jinjatools test --cov jinjatools --cov test --cov-report term-missing
  - tox -r -v

  - pip install zetup[all]
  - zetup install
  # - zetup pytest
  - zetup sdist
  - zetup tox
