language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install zetup[commands]
  - zetup install
  - pip install pytest pytest-cov

script:
  # - zetup pytest
  - python -m pytest --doctest-modules test --cov jinjatools --cov-report term-missing
